version: '3'

services:
  # mariadb
  db:
    image: mariadb:10
    container_name: smp-mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    env_file: db.my.env
    volumes:
      - ./smp-db/conf.d:/etc/mysql/conf.d
      - ./smp-db/initdb.d:/docker-entrypoint-initdb.d
      - smpmydb_data:/var/lib/mysql # docker volume

  # postgresql
  # db:
  #   image: postgres:14
  #   container_name: smp-pgsql
  #   restart: always
  #   env_file:
  #     - db.pg.env
  #   ports:
  #     - "5432:5432/tcp"
  #   volumes:
  #     - smppgdb_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: smp-mongo
    restart: always
    ports:
      - 27017:27017/tcp
    environment:
      MONGO_INITDB_ROOT_USERNAME: tonyne
      MONGO_INITDB_ROOT_PASSWORD: tonyne
    volumes:
      - smpmg_data:/data/db
      - smpmg_cfg:/data/configdb

  api:
    image: py39-slim
    container_name: smp-api
    build: ./smp-api
    command: poetry run python app/main.py
    env_file:
      - api.env
    depends_on:
      - db
      - mongo
    links:
      - db
      - mongo
    ports:
      - 58000:8000
    volumes:
      - smpapi_data:/app

volumes:
  smppgdb_data:
    name: smppgdb_data
  smpmydb_data:
    name: smpmydb_data
  smpmg_data:
    name: smpmg_data
  smpmg_cfg:
    name: smpmg_cfg
  smpapi_data:
    name: smpapi_data
